#!/usr/bin/env bash
set -euo pipefail

# archive_uploads.sh
# Idempotent script to:
#  - ensure uploads/ is listed in .gitignore
#  - create a compressed archive uploads.tar.gz from uploads/
#  - stage .gitignore and uploads.tar.gz, commit, and attempt to push
# Usage: ./backend/scripts/archive_uploads.sh [--no-push]

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
# Backend directory (script is in backend/scripts)
BACKEND_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
# Workspace root is parent of backend
WORKSPACE_ROOT="$(cd "$BACKEND_DIR/.." && pwd -P)"
# Determine git repo root if available, else use workspace root
GIT_ROOT="$(git -C "$WORKSPACE_ROOT" rev-parse --show-toplevel 2>/dev/null || true)"
if [ -n "$GIT_ROOT" ]; then
  REPO_ROOT="$GIT_ROOT"
else
  REPO_ROOT="$WORKSPACE_ROOT"
fi

GIT_DIR="$REPO_ROOT"
GIT_IGNORE="$BACKEND_DIR/.gitignore"
UPLOADS_DIR="$BACKEND_DIR/uploads"
ARCHIVE_PATH="$BACKEND_DIR/uploads.tar.gz"

NO_PUSH=false
if [[ "${1-}" == "--no-push" ]]; then
  NO_PUSH=true
fi

echo "Repo root: $REPO_ROOT"

# Ensure .gitignore has uploads/
if ! grep -qxF "uploads/" "$GIT_IGNORE" 2>/dev/null; then
  echo "Adding uploads/ to .gitignore"
  printf "\n# Ignore uploaded media stored locally\nuploads/\n" >> "$GIT_IGNORE"
else
  echo "uploads/ already in .gitignore"
fi

if [ ! -d "$UPLOADS_DIR" ]; then
  echo "No uploads directory found at $UPLOADS_DIR. Nothing to archive."
  exit 0
fi

echo "Creating compressed archive at $ARCHIVE_PATH"
tar -C "$BACKEND_DIR" -czf "$ARCHIVE_PATH" "uploads"

cd "$GIT_DIR"

# Check if this workspace is a git repository
if git -C "$GIT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  echo "Staging .gitignore and uploads.tar.gz"
  git add --force "$ARCHIVE_PATH" "$GIT_IGNORE"

  COMMIT_MSG="chore: ignore uploads/ and add uploads.tar.gz archive (generated by archive_uploads.sh)"
  if git diff --staged --quiet; then
    echo "No changes to commit"
  else
    git commit -m "$COMMIT_MSG"
    echo "Committed: $COMMIT_MSG"
  fi

  if [ "$NO_PUSH" = false ]; then
    echo "Attempting to push to remote 'origin' on current branch"
    CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
    if git remote get-url origin >/dev/null 2>&1; then
      if git push origin "$CURRENT_BRANCH"; then
        echo "Push successful"
      else
        echo "Push failed — check credentials or remote settings" >&2
        exit 2
      fi
    else
      echo "No 'origin' remote configured; skipping push"
    fi
  else
    echo "--no-push specified; skipping push step"
  fi
else
  echo "Not a git repository; skipping git add/commit/push steps"
fi

echo "Done."
